config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  get "/anynomous", to: "users#anynomous", as: :anon
  get "/tags/:tag", to: "articles#index", as: :tag

  devise_for :users
  resources :articles do
    resources :comments
  end
  resources :users do
    member do
      get :follwoing, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
end

app/models/article.rb
class Article < ActiveRecord::Base
    acts_as_taggable
    acts_as_taggable_on :topics
    validates :title, presence: true, length: { minimum: 5 }
    validates :slug, presence: true, uniqueness: { case_sensitive: false }
    belongs_to :user
    has_many :comments

    def to_param
      slug
    end

    def next
      self.class.where("id > :id",id: id).take(1)
    end

    def prev
      self.class.where("id < :id",id: id).take(1)
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_attached_file :avatar, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = "SELECT followed_id FROM Relationships WHERE follower_id = :user_id"
    Article.where("user_id IN (#{following_ids}) OR user_id = :user_id OR anon = true", user_id: id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def to_slug(title)
    #strip the string
    ret = title.strip

    #blow away apostrophes
    ret.gsub! /['`]/,""

    # @ --> at, and & --> and
    ret.gsub! /\s*@\s*/, " at "
    ret.gsub! /\s*&\s*/, " and "

    #replace all non alphanumeric, underscore or periods with underscore
     ret.gsub! /\s*[^A-Za-z0-9\.\-]\s*/, '-'

     #convert double underscores to single
     ret.gsub! /_+/,"-"

     #strip off leading/trailing underscore
     ret.gsub! /\A[_\.]+|[_\.]+\z/,""

     ret
  end

  def randomString(far)
    (0..far.to_i).map { ("a".."z").to_a[rand(26)] }.join
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  before_action :fetch_article, except: [:index, :new, :create]

  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 10)
    elsif current_user
      @articles = current_user.feed.paginate(page: params[:page], per_page: 10).order("created_at desc")
    else
      @articles = Article.paginate(page: params[:page], per_page: 10).order("created_at desc")
    end

    respond_to do |format|
      format.html { @articles }
      format.json { render json: @articles }
    end
  end

  def new
    @article = current_user.articles.build
  end

  def edit; end

  def update
    @article.save

    respond_to do |format|
      if @article.update(article_params)
        @saved = true
        format.html { redirect_to @article }
        format.js
        format.json { @article }
      else
        @saved = false
        format.html { redirect_to 'new' }
        format.js
        format.json { @article }
      end
    end
  end

  def create
    @article = current_user.articles.build(article_params)
    @article.slug = "#{to_slug(params[:article][:title])}-#{randomString(6)}"
    @article.anon = params[:anon]

    respond_to do |format|
      if @article.save
        @saved = true
        format.html { redirect_to @article }
        format.js
        format.json { @article }
      else
        @saved = false
        format.html { redirect_to 'new' }
        format.js
        format.json { @article }
      end
    end
  end

  def show
    @comments = Comment.where(article_id: @article.id)
    # all is not required after using where
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private
  
  # Don't have to add indentation to show private method. You can only add one empty line
  # https://github.com/bbatsov/ruby-style-guide#consistent-classes
  def article_params
    published = params[:publish] ? 1 : 0
    params.require(:article).permit(:title, :content, :topic_list).merge(published: published)
    # Add space between each attributes. 
  end
  
  def fetch_article
    @article = Article.find_by_slug(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:comment][:id])
    @comment = @article.comments.new

    @comment.user_id = current_user.id
    @comment.content = params[:comment][:content]
    if @comment.save
      respond_to do |format|
        format.html { redirect_to article_path(@article) }
        format.js
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
      format.json { @user }
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
      format.json { @user }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		render plain: "Halo"
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if :avatar.empty?
			@user.update(params[:name,:bio])
		else
			if @user.update(user_params)
				redirect_to @user
			end
		end
	end

	def anynomous
		@articles = Article.where('anon = true').all
	end

	private
		def user_params
			params.require(:user).permit(:avatar,:name,:bio)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Rails Blog"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div class="row">
  <% if @article.errors.any? %>
      <div class="alert alert-danger">
          <ul>
              <% @article.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
          </ul>
      </div>
  <% end %>

  <%= form_for @article, remote: true do |f| %>

  <div class="col-md-8">
    <div class="form-group">
        <%= f.text_field :title, class: 'form-control input-lg', placeholder: 'Title here ..' %>
    </div>

    <div class="form-group">
        <%= f.text_area :content, class: 'summernote', style: 'height: 250px' %>
    </div>
  </div>

  <div class="col-md-4">
    <div class="row">
      <div class="col-xs-12">
        <div class="form-group">
          <label>Post As</label>

          <select name="anon" class="form-control">
            <option value="false"><%= current_user.name %></option>
            <option value="true">Anynomous</option>
          </select>
        </div>

        <div class="form-group">
          <label>Tag</label>
          <%= f.text_field :topic_list, class: 'form-control', placeholder: 'Separate by comma (,)' %>
        </div>
      </div>

      <div class="col-xs-12">
        <div class="btn-group" role="group">
          <input type="submit" value="Save to Draft" class="btn btn-default btn-lg" data-loading-text="Saving ..." name="draft" id="draft-btn">
          <input type="submit" value="Publish" class="btn btn-primary btn-lg" data-loading-text="Saving ..." name="publish" id="publish-btn">
        </div>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/articles/create.js.erb
var $saved = "<%= @saved %>";
var $published = "<%= @article.published %>";
if ($saved && $published) {
  window.location.assign("/articles/" + "<%= @article.slug %>");
}else if($saved && !$published){
  alert("Saved to draft");
  $("#draft-btn").button('reset');
}else{
  alert("errors");
}

app/views/articles/edit.html.erb
<% provide(:title, "Edit #{@article.title}") %>
<div class="container">
  <header class="page-header">
    <h1>Edit Article</h1>
  </header>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <header class="page-header">
              <h1 class="home-quotes">
                "Sebab apalagi yang disisakan kematian, selain kenangan dan kata-kata."
              </h1>
            </header>
            <% @articles.each do |item| %>
              <%= render 'partials/article_list',item: item if item.published? %>
            <% end %>

            <%= will_paginate @articles %>
        </div>
    </div>
</div>

app/views/articles/new.html.erb
<% provide(:title, "New Article") %>
<div class="container">
  <header class="page-header">
    <h1>Create Article</h1>
  </header>
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <article class="details">
                <header class="page-header">
                    <h1>
                        <%= @article.title %>
                    </h1>
                    <% if @article.anon? %>
                      <%= link_to image_tag('anon-thumb.jpg', class: 'img-circle', style: 'width:38px; margin-right: 5px'), anon_path %>
                      <small><%= link_to 'Anynomous', anon_path %></small>
                    <% else %>
                      <%= link_to image_tag(@article.user.avatar.url(:thumb), class: 'img-circle', style: 'width:38px; margin-right: 5px'), @article.user %>
                      <small><%= link_to @article.user.name, @article.user %></small>
                    <% end %>
                    <% if current_user == @article.user %>
                      <%= link_to 'Edit', edit_article_path(@article) %>
                      <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Kamu yakin ?' } %>
                    <% end %>
                </header>

                <section>
                    <%= @article.content.html_safe %>
                </section>
                <br>
                <small>Tags : <%= render('partials/tags',{tags: @article.topics}) %></small>
            </article>
            <br>

            <header class="page-header">
              <% if @article.comments.empty? %>
                <% if user_signed_in? %>
                  <h4>Be The First commenter to this article !</h4>
                <% end %>
              <% else %>
                <h4>This article have <%= @article.comments.length %> comments</h4>
              <% end %>
            </header>

            <div id="comments">
              <% @comments.each do |item| %>
                <div class="media" id="edit_comment_<%= item.id %>">
                  <div class="media-left">
                    <a href="<%= user_path(item.user.id) %>">
                      <%= image_tag item.user.avatar.url(:thumb), class: "media-object img-circle", width:"70px" %>
                    </a>
                  </div>
                  <div class="media-body">
                    <h4 class="media-heading">
                      <%= item.user.name %> at
                      <small><%= time_ago_in_words(item.created_at) %> ago</small>
                      <div class="pull-right">
                        <%= link_to '<small><i class="fa fa-trash"></i> delete</small>'.html_safe, article_comment_path(@article.id, item.id), method: :delete, remote: true, data: {confirm: "Are you sure ?"}, class: 'text-danger' %>
                      </div>
                    </h4>
                    <%= item.content.html_safe %>
                  </div>
                  <hr>
                </div>
              <% end %>
            </div>

            <% if user_signed_in? %>
              <div id="form-comment">
                <%= form_for([@article, @article.comments.build], remote: true) do |f| %>
                  <div class="hidden">
                    <%= f.text_field :id, value: @article.id %>
                  </div>
                  <div class="media">
                    <div class="media-left">
                      <%= image_tag current_user.avatar.url(:thumb), class: "media-object img-circle", width:"70px" %>
                    </div>
                    <div class="media-body">
                      <%= f.text_field :content, class: "form-control comment-field", placeholder: "What do you say ?" %>
                    </div>
                  </div>
                  <div class="hidden">
                    <%= f.submit "Save Comment", class: 'btn btn-primary' %>
                  </div>
                <% end %>
              </div>
            <% end %>
        </div>
    </div>
</div>

app/views/articles/update.js.erb
var $saved = "<%= @saved %>";
var $published = "<%= @article.published %>";
if ($saved && $published) {
  window.location.assign("/articles/" + "<%= @article.slug %>");
}else if($saved && !$published){
  alert("Saved to draft");
  $("#draft-btn").button('reset');
}else{
  alert("errors");
}

app/views/comments/create.js.erb
$("#comments").append(
  '<div class="media" id="edit_comment_<%= @comment.id %>">' +
    '<div class="media-left">' +
      '<a href="<%= user_path(@comment.user.id) %>">' +
        '<%= image_tag @comment.user.avatar.url(:thumb), class: "media-object img-rounded", width:"70px" %>' +
      '</a>' +
    '</div>' +
    '<div class="media-body">' +
      '<h4 class="media-heading"><%= @comment.user.name %> at <small><%= time_ago_in_words(@comment.created_at) %>' +
      ' ago</small>' +
      '</h4>' +
      '<div class="pull-right">' +
        '<%= link_to "<small>delete</small>".html_safe, article_comment_path(@article.id, @comment.id), method: :delete, remote: true, data: {confirm: "Are you sure ?"} %> ' +
      '</div>' +
      '<%= @comment.content.html_safe %>' +
    '</div><hr>' +
  '</div>'
);
$("#comment_content").val("");

app/views/comments/destroy.js.erb
$("#edit_comment_<%= @comment.id %>").remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to image_tag('logo.svg',width: '35px'), articles_path, class: 'navbar-brand' %>
            </div>

            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                  <li>
                    <%= link_to "<i class='fa fa-home'></i> Home".html_safe, articles_path %>
                  </li>
                  <li>
                    <a href="">Popular</a>
                  </li>
                  <li>
                    <a href="">
                      Bundle
                    </a>
                  </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <% if user_signed_in? %>
                      <li><%= link_to '<i class="fa fa-pencil-square-o"></i> Write'.html_safe, new_article_path %></li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag current_user.avatar.url(:thumb), style: "width:30px;margin-top:-10px;margin-bottom:-5px;",class: "img-circle" %><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Profile", current_user %></li>
                          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
                        </ul>
                      </li>
                    <% else %>
                      <li><%= link_to 'Sign In', new_user_session_path %></li>
                    <% end %>
                </ul>
            </div>
          </div>
        </div>
    </div>
</nav>

<%= yield %>

</body>
</html>

app/views/partials/_article_list.html.erb
<article class="home-lists">
    <div class="profile-details-feed">
      <% if item.anon? %>
        <%= image_tag('anon-thumb.jpg', class: "img-circle") %>
      <% else %>
        <%= image_tag(item.user.avatar.url(:thumb), class: "img-circle") %>
      <% end %>
      <span>
        <% if item.anon? %>
          <%= link_to "anynomous", anon_path %> <br>
        <% else %>
          <%= link_to item.user.name, item.user %> <br>
        <% end %>
        <small class="mute"><%= time_ago_in_words(item.created_at) %> ago</small>
      </span>
    </div>
    <header>
        <h2><%= link_to item.title, item %></h2>
    </header>
    <section>
        <%= ("<p>" + item.content[0..250] + "<p>").html_safe %>
    </section>
    <hr>
    <small>
      Tags : <%= render('partials/tags',{tags: item.topics}) %>
      <br>
      <%= item.comments.length %> Comments
    </small>
</article>

app/views/partials/_tags.html.erb
<% unless tags.empty? %>
  <% tags.each do |item| %>
    <div class="tags">
      <%= link_to item.name, tag_path(item.name) %>
    </div>
  <% end %>
<% end %>

app/views/relationships/create.js.erb
$("#follow-form").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html("<%= @user.followers.count %>")

app/views/relationships/destroy.js.erb
$("#follow-form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html("<%= @user.followers.count %>")

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.
                          build(followed_id: @user.id),
                          remote: true) do |f| %>
  <%= f.hidden_field :followed_id %>
  <%= f.submit "Follow", class: "btn btn-default btn-rounded btn-lg" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<div class="form-group">
		<label>Avatar</label>
		<%= f.file_field :avatar, class: 'form-control input-lg' %>
	</div>

	<div class="form-group">
		<label>Name</label>
		<%= f.text_field :name, class: 'form-control input-lg' %>
	</div>

	<div class="form-group">
		<label>Name</label>
		<%= f.text_area :bio, class: 'summernote' %>
	</div>

	<div class="form-group">
		<label>Email</label>
		<%= f.text_field :email, class: 'form-control input-lg', disabled: "true" %>
	</div>

	<p class="text-center">
		<%= f.submit 'Save', class: 'btn btn-primary btn-lg btn-block' %>
	</p>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.
                          find_by(followed_id: @user.id),
                          method: :delete,
                          remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-default btn-rounded btn-lg" %>
<% end %>

app/views/users/anynomous.html.erb
<% provide :title, 'Anynomous' %>
<div class="container" style="padding-top:50px">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="text-center">
				<%= image_tag 'anon-medium.jpg', class: "img-circle" %>
			</div>
			<header class="page-header text-center">
				<h2>
					<%= "Anynomous" %>
					<br>
					<small><%= @articles.length %> Articles </small>
				</h2>
			</header>

			<% @articles.reverse.each do |item| %>
				<%= render 'partials/article_list',item: item %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<% provide :title, "Edit #{@user.name}" %>
<div class="container" style="padding-top:50px">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="container" style="padding-top:50px">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="text-center">
				<%= image_tag @user.avatar.url(:medium), class: "img-circle" %>
			</div>
			<header class="page-header text-center">
				<h2>
					<%= @user.name %>
					<br>
					<small><%= @user.articles.length %> Articles <span id="followers"><%= @user.followers.count %></span> Followers <span id="following"><%= @user.following.count %></span> Following</small>
				</h2>
				<% if current_user == @user %>
					<div>
						<%= link_to 'Settings', edit_user_path(@user.id), class: "btn btn-default btn-rounded btn-lg" %>
					</div>
				<% end %>
				<% if user_signed_in? && current_user != @user %>
					<div id="follow-form">
						<% if current_user.following?(@user) %>
							<%= render 'unfollow' %>
						<% else %>
							<%= render 'follow' %>
						<% end %>
					</div>
				<% end %>
			</header>

			<% @user.articles.reverse.each do |item| %>
				<% unless item.anon? %>
					<%= render 'partials/article_list',item: item %>
				<% end %>
			<% end %>
		</div>
	</div>
</div>